// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYcGgxMKVh7r3frmtj_73Gw_GJq3Vs68',
    appId: '1:591066052512:web:2c95d689fd513f890a96c5',
    messagingSenderId: '591066052512',
    projectId: 'aman-singh-ff244',
    authDomain: 'aman-singh-ff244.firebaseapp.com',
    storageBucket: 'aman-singh-ff244.firebasestorage.app',
    measurementId: 'G-XKBVEGJ60M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhexTFGOFRdQ59nujODHGc4-skSHcpZo',
    appId: '1:591066052512:android:a853caf2514b26d40a96c5',
    messagingSenderId: '591066052512',
    projectId: 'aman-singh-ff244',
    storageBucket: 'aman-singh-ff244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSmuT07_jQONrBCIWq2NTMxo8e3_hPAwI',
    appId: '1:591066052512:ios:45cc3255aec15bca0a96c5',
    messagingSenderId: '591066052512',
    projectId: 'aman-singh-ff244',
    storageBucket: 'aman-singh-ff244.firebasestorage.app',
    iosBundleId: 'aman.com.amanSingh',
  );
}
